/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export type ShedId = bigint;
export type AnimalId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TubChangeEntry {
    id: TubChangeId;
    animalId: AnimalId;
    timestamp: Time;
}
export type WeightId = bigint;
export interface ClutchEntry {
    id: bigint;
    animalId: AnimalId;
    notes: string;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AnimalWithDaysSinceLastMealAndPairing {
    daysSinceLastPairing?: bigint;
    animal: Animal;
    daysSinceLastMeal?: bigint;
}
export interface AnimalWeightUpdate {
    weight: bigint;
    animalId: AnimalId;
}
export interface ShedEntry {
    id: ShedId;
    animalId: AnimalId;
    timestamp: Time;
}
export type IdNumber = string;
export interface PairingEntry {
    id: PairingId;
    animalId: AnimalId;
    notes: string;
    timestamp: Time;
}
export interface BulkSnakeEntry {
    sex: string;
    weight?: bigint;
    name: string;
    picture?: ExternalBlob;
    idNumber: IdNumber;
    genes: string;
    birthday?: Time;
}
export interface ClutchInput {
    clutchNumber: bigint;
    outcomeNotes: string;
    numSlugs: bigint;
    dateEggsLaid: Time;
    sireId: AnimalId;
    numEggsLaid: bigint;
    damId: AnimalId;
    hatchDate?: Time;
    numHatched: bigint;
}
export interface Animal {
    id: AnimalId;
    sex: string;
    weight?: bigint;
    name: string;
    picture?: ExternalBlob;
    idNumber: IdNumber;
    genes: string;
    birthday?: Time;
}
export interface Meal {
    id: MealId;
    animalId: AnimalId;
    timestamp: Time;
    details: string;
}
export type TubChangeId = bigint;
export interface ClutchRecord {
    id: ClutchId;
    clutchNumber: bigint;
    outcomeNotes: string;
    numSlugs: bigint;
    dateEggsLaid: Time;
    sireId: AnimalId;
    numEggsLaid: bigint;
    damId: AnimalId;
    hatchDate?: Time;
    numHatched: bigint;
}
export interface AnimalWithDaysSinceLastEvents {
    daysSinceLastPairing?: bigint;
    animal: Animal;
    daysSinceLastClutch?: bigint;
    daysSinceLastTubChange?: bigint;
    daysSinceLastMeal?: bigint;
    daysSinceLastShed?: bigint;
}
export type PairingId = bigint;
export interface AnimalWithDaysSinceLastMeal {
    animal: Animal;
    daysSinceLastMeal?: bigint;
}
export type MealId = bigint;
export interface WeightEntry {
    id: WeightId;
    weight: bigint;
    animalId: AnimalId;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export type ClutchId = bigint;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAnimal(name: string, genes: string, sex: string, birthday: Time | null, weight: bigint | null, picture: ExternalBlob | null, idNumber: IdNumber): Promise<AnimalId>;
    addBulkMealsForSelectedAnimals(animalIds: Array<AnimalId>, details: string, timestamp: Time): Promise<Array<MealId>>;
    addBulkSnakes(snakes: Array<BulkSnakeEntry>): Promise<Array<AnimalId>>;
    addBulkWeightEntries(weightEntries: Array<WeightEntry>): Promise<void>;
    addBulkWeightsForSelectedAnimals(weightUpdates: Array<AnimalWeightUpdate>): Promise<void>;
    addClutchRecord(clutchInput: ClutchInput): Promise<ClutchId>;
    addMeal(animalId: AnimalId, details: string, timestamp: Time): Promise<MealId>;
    addPairingEntry(animalId: AnimalId, timestamp: Time, notes: string): Promise<PairingId>;
    addWeightEntry(animalId: AnimalId, weight: bigint, timestamp: Time): Promise<WeightId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAnimal(id: AnimalId): Promise<void>;
    deleteClutchEntry(id: bigint): Promise<void>;
    deleteClutchRecord(id: ClutchId): Promise<void>;
    deleteMeal(id: MealId): Promise<void>;
    deletePairingEntry(id: PairingId): Promise<void>;
    deleteShedEntry(id: ShedId): Promise<void>;
    deleteTubChangeEntry(id: TubChangeId): Promise<void>;
    deleteWeightEntry(id: WeightId): Promise<void>;
    editAnimal(id: AnimalId, name: string, genes: string, sex: string, birthday: Time | null, weight: bigint | null, picture: ExternalBlob | null, idNumber: IdNumber): Promise<void>;
    editClutchEntry(id: bigint, animalId: AnimalId, timestamp: Time, notes: string): Promise<void>;
    editClutchRecord(id: ClutchId, clutchInput: ClutchInput): Promise<void>;
    editMeal(id: MealId, details: string): Promise<void>;
    editPairingEntry(id: PairingId, timestamp: Time, notes: string): Promise<void>;
    editShedEntry(id: ShedId, animalId: AnimalId, timestamp: Time): Promise<void>;
    editTubChangeEntry(id: TubChangeId, animalId: AnimalId, timestamp: Time): Promise<void>;
    editWeightEntry(id: WeightId, weight: bigint, timestamp: Time): Promise<void>;
    getAnimalById(id: AnimalId): Promise<Animal | null>;
    getAnimals(): Promise<Array<Animal>>;
    getAnimalsWithDaysSinceLastEvents(): Promise<Array<AnimalWithDaysSinceLastEvents>>;
    getAnimalsWithDaysSinceLastMeal(): Promise<Array<AnimalWithDaysSinceLastMeal>>;
    getAnimalsWithDaysSinceLastMealAndPairing(): Promise<Array<AnimalWithDaysSinceLastMealAndPairing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClutchHistoryForAnimal(animalId: AnimalId): Promise<Array<ClutchEntry>>;
    getClutchRecords(): Promise<Array<ClutchRecord>>;
    getCustomHeading(): Promise<string>;
    getLastWaterChange(): Promise<Time | null>;
    getMealsForAnimal(animalId: AnimalId): Promise<Array<Meal>>;
    getPairingHistoryForAnimal(animalId: AnimalId): Promise<Array<PairingEntry>>;
    getShedHistoryForAnimal(animalId: AnimalId): Promise<Array<ShedEntry>>;
    getTubChangeHistoryForAnimal(animalId: AnimalId): Promise<Array<TubChangeEntry>>;
    getUserLogo(): Promise<ExternalBlob | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightHistoryForAnimal(animalId: AnimalId): Promise<Array<WeightEntry>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logShedAndTubChange(animalId: AnimalId): Promise<void>;
    logShedOnly(animalId: AnimalId): Promise<void>;
    logTubChangeOnly(animalId: AnimalId): Promise<void>;
    recordClutch(animalId: AnimalId, notes: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCustomHeading(heading: string): Promise<void>;
    updateWaterChange(): Promise<void>;
    uploadUserLogo(logo: ExternalBlob): Promise<void>;
}
import type { Animal as _Animal, AnimalId as _AnimalId, AnimalWithDaysSinceLastEvents as _AnimalWithDaysSinceLastEvents, AnimalWithDaysSinceLastMeal as _AnimalWithDaysSinceLastMeal, AnimalWithDaysSinceLastMealAndPairing as _AnimalWithDaysSinceLastMealAndPairing, BulkSnakeEntry as _BulkSnakeEntry, ClutchId as _ClutchId, ClutchInput as _ClutchInput, ClutchRecord as _ClutchRecord, ExternalBlob as _ExternalBlob, IdNumber as _IdNumber, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAnimal(arg0: string, arg1: string, arg2: string, arg3: Time | null, arg4: bigint | null, arg5: ExternalBlob | null, arg6: IdNumber): Promise<AnimalId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnimal(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnimal(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async addBulkMealsForSelectedAnimals(arg0: Array<AnimalId>, arg1: string, arg2: Time): Promise<Array<MealId>> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkMealsForSelectedAnimals(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkMealsForSelectedAnimals(arg0, arg1, arg2);
            return result;
        }
    }
    async addBulkSnakes(arg0: Array<BulkSnakeEntry>): Promise<Array<AnimalId>> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkSnakes(await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkSnakes(await to_candid_vec_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBulkWeightEntries(arg0: Array<WeightEntry>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkWeightEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkWeightEntries(arg0);
            return result;
        }
    }
    async addBulkWeightsForSelectedAnimals(arg0: Array<AnimalWeightUpdate>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkWeightsForSelectedAnimals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkWeightsForSelectedAnimals(arg0);
            return result;
        }
    }
    async addClutchRecord(arg0: ClutchInput): Promise<ClutchId> {
        if (this.processError) {
            try {
                const result = await this.actor.addClutchRecord(to_candid_ClutchInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClutchRecord(to_candid_ClutchInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMeal(arg0: AnimalId, arg1: string, arg2: Time): Promise<MealId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeal(arg0, arg1, arg2);
            return result;
        }
    }
    async addPairingEntry(arg0: AnimalId, arg1: Time, arg2: string): Promise<PairingId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPairingEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPairingEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addWeightEntry(arg0: AnimalId, arg1: bigint, arg2: Time): Promise<WeightId> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAnimal(arg0: AnimalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnimal(arg0);
            return result;
        }
    }
    async deleteClutchEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClutchEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClutchEntry(arg0);
            return result;
        }
    }
    async deleteClutchRecord(arg0: ClutchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClutchRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClutchRecord(arg0);
            return result;
        }
    }
    async deleteMeal(arg0: MealId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeal(arg0);
            return result;
        }
    }
    async deletePairingEntry(arg0: PairingId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePairingEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePairingEntry(arg0);
            return result;
        }
    }
    async deleteShedEntry(arg0: ShedId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShedEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShedEntry(arg0);
            return result;
        }
    }
    async deleteTubChangeEntry(arg0: TubChangeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTubChangeEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTubChangeEntry(arg0);
            return result;
        }
    }
    async deleteWeightEntry(arg0: WeightId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeightEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeightEntry(arg0);
            return result;
        }
    }
    async editAnimal(arg0: AnimalId, arg1: string, arg2: string, arg3: string, arg4: Time | null, arg5: bigint | null, arg6: ExternalBlob | null, arg7: IdNumber): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editAnimal(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editAnimal(arg0, arg1, arg2, arg3, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async editClutchEntry(arg0: bigint, arg1: AnimalId, arg2: Time, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editClutchEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editClutchEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async editClutchRecord(arg0: ClutchId, arg1: ClutchInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editClutchRecord(arg0, to_candid_ClutchInput_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editClutchRecord(arg0, to_candid_ClutchInput_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async editMeal(arg0: MealId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMeal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMeal(arg0, arg1);
            return result;
        }
    }
    async editPairingEntry(arg0: PairingId, arg1: Time, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPairingEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPairingEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async editShedEntry(arg0: ShedId, arg1: AnimalId, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editShedEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editShedEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async editTubChangeEntry(arg0: TubChangeId, arg1: AnimalId, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTubChangeEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTubChangeEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async editWeightEntry(arg0: WeightId, arg1: bigint, arg2: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editWeightEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editWeightEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async getAnimalById(arg0: AnimalId): Promise<Animal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimalById(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimalById(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimals(): Promise<Array<Animal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimals();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimals();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimalsWithDaysSinceLastEvents(): Promise<Array<AnimalWithDaysSinceLastEvents>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimalsWithDaysSinceLastEvents();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimalsWithDaysSinceLastEvents();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimalsWithDaysSinceLastMeal(): Promise<Array<AnimalWithDaysSinceLastMeal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimalsWithDaysSinceLastMeal();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimalsWithDaysSinceLastMeal();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimalsWithDaysSinceLastMealAndPairing(): Promise<Array<AnimalWithDaysSinceLastMealAndPairing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimalsWithDaysSinceLastMealAndPairing();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimalsWithDaysSinceLastMealAndPairing();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClutchHistoryForAnimal(arg0: AnimalId): Promise<Array<ClutchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClutchHistoryForAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClutchHistoryForAnimal(arg0);
            return result;
        }
    }
    async getClutchRecords(): Promise<Array<ClutchRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClutchRecords();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClutchRecords();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomHeading(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomHeading();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomHeading();
            return result;
        }
    }
    async getLastWaterChange(): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastWaterChange();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastWaterChange();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMealsForAnimal(arg0: AnimalId): Promise<Array<Meal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMealsForAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMealsForAnimal(arg0);
            return result;
        }
    }
    async getPairingHistoryForAnimal(arg0: AnimalId): Promise<Array<PairingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairingHistoryForAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairingHistoryForAnimal(arg0);
            return result;
        }
    }
    async getShedHistoryForAnimal(arg0: AnimalId): Promise<Array<ShedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShedHistoryForAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShedHistoryForAnimal(arg0);
            return result;
        }
    }
    async getTubChangeHistoryForAnimal(arg0: AnimalId): Promise<Array<TubChangeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTubChangeHistoryForAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTubChangeHistoryForAnimal(arg0);
            return result;
        }
    }
    async getUserLogo(): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLogo();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLogo();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightHistoryForAnimal(arg0: AnimalId): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightHistoryForAnimal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightHistoryForAnimal(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logShedAndTubChange(arg0: AnimalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logShedAndTubChange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logShedAndTubChange(arg0);
            return result;
        }
    }
    async logShedOnly(arg0: AnimalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logShedOnly(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logShedOnly(arg0);
            return result;
        }
    }
    async logTubChangeOnly(arg0: AnimalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logTubChangeOnly(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logTubChangeOnly(arg0);
            return result;
        }
    }
    async recordClutch(arg0: AnimalId, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordClutch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordClutch(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setCustomHeading(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCustomHeading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCustomHeading(arg0);
            return result;
        }
    }
    async updateWaterChange(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWaterChange();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWaterChange();
            return result;
        }
    }
    async uploadUserLogo(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadUserLogo(await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadUserLogo(await to_candid_ExternalBlob_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AnimalWithDaysSinceLastEvents_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimalWithDaysSinceLastEvents): Promise<AnimalWithDaysSinceLastEvents> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_AnimalWithDaysSinceLastMealAndPairing_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimalWithDaysSinceLastMealAndPairing): Promise<AnimalWithDaysSinceLastMealAndPairing> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_AnimalWithDaysSinceLastMeal_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimalWithDaysSinceLastMeal): Promise<AnimalWithDaysSinceLastMeal> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Animal_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Animal): Promise<Animal> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ClutchRecord_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClutchRecord): ClutchRecord {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Animal]): Promise<Animal | null> {
    return value.length === 0 ? null : await from_candid_Animal_n20(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnimalId;
    sex: string;
    weight: [] | [bigint];
    name: string;
    picture: [] | [_ExternalBlob];
    idNumber: _IdNumber;
    genes: string;
    birthday: [] | [_Time];
}): Promise<{
    id: AnimalId;
    sex: string;
    weight?: bigint;
    name: string;
    picture?: ExternalBlob;
    idNumber: IdNumber;
    genes: string;
    birthday?: Time;
}> {
    return {
        id: value.id,
        sex: value.sex,
        weight: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.weight)),
        name: value.name,
        picture: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.picture)),
        idNumber: value.idNumber,
        genes: value.genes,
        birthday: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.birthday))
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daysSinceLastPairing: [] | [bigint];
    animal: _Animal;
    daysSinceLastClutch: [] | [bigint];
    daysSinceLastTubChange: [] | [bigint];
    daysSinceLastMeal: [] | [bigint];
    daysSinceLastShed: [] | [bigint];
}): Promise<{
    daysSinceLastPairing?: bigint;
    animal: Animal;
    daysSinceLastClutch?: bigint;
    daysSinceLastTubChange?: bigint;
    daysSinceLastMeal?: bigint;
    daysSinceLastShed?: bigint;
}> {
    return {
        daysSinceLastPairing: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastPairing)),
        animal: await from_candid_Animal_n20(_uploadFile, _downloadFile, value.animal),
        daysSinceLastClutch: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastClutch)),
        daysSinceLastTubChange: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastTubChange)),
        daysSinceLastMeal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastMeal)),
        daysSinceLastShed: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastShed))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    animal: _Animal;
    daysSinceLastMeal: [] | [bigint];
}): Promise<{
    animal: Animal;
    daysSinceLastMeal?: bigint;
}> {
    return {
        animal: await from_candid_Animal_n20(_uploadFile, _downloadFile, value.animal),
        daysSinceLastMeal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastMeal))
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    daysSinceLastPairing: [] | [bigint];
    animal: _Animal;
    daysSinceLastMeal: [] | [bigint];
}): Promise<{
    daysSinceLastPairing?: bigint;
    animal: Animal;
    daysSinceLastMeal?: bigint;
}> {
    return {
        daysSinceLastPairing: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastPairing)),
        animal: await from_candid_Animal_n20(_uploadFile, _downloadFile, value.animal),
        daysSinceLastMeal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.daysSinceLastMeal))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ClutchId;
    clutchNumber: bigint;
    outcomeNotes: string;
    numSlugs: bigint;
    dateEggsLaid: _Time;
    sireId: _AnimalId;
    numEggsLaid: bigint;
    damId: _AnimalId;
    hatchDate: [] | [_Time];
    numHatched: bigint;
}): {
    id: ClutchId;
    clutchNumber: bigint;
    outcomeNotes: string;
    numSlugs: bigint;
    dateEggsLaid: Time;
    sireId: AnimalId;
    numEggsLaid: bigint;
    damId: AnimalId;
    hatchDate?: Time;
    numHatched: bigint;
} {
    return {
        id: value.id,
        clutchNumber: value.clutchNumber,
        outcomeNotes: value.outcomeNotes,
        numSlugs: value.numSlugs,
        dateEggsLaid: value.dateEggsLaid,
        sireId: value.sireId,
        numEggsLaid: value.numEggsLaid,
        damId: value.damId,
        hatchDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.hatchDate)),
        numHatched: value.numHatched
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Animal>): Promise<Array<Animal>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Animal_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimalWithDaysSinceLastEvents>): Promise<Array<AnimalWithDaysSinceLastEvents>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnimalWithDaysSinceLastEvents_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimalWithDaysSinceLastMeal>): Promise<Array<AnimalWithDaysSinceLastMeal>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnimalWithDaysSinceLastMeal_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimalWithDaysSinceLastMealAndPairing>): Promise<Array<AnimalWithDaysSinceLastMealAndPairing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnimalWithDaysSinceLastMealAndPairing_n34(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClutchRecord>): Array<ClutchRecord> {
    return value.map((x)=>from_candid_ClutchRecord_n40(_uploadFile, _downloadFile, x));
}
async function to_candid_BulkSnakeEntry_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BulkSnakeEntry): Promise<_BulkSnakeEntry> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ClutchInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClutchInput): _ClutchInput {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sex: string;
    weight?: bigint;
    name: string;
    picture?: ExternalBlob;
    idNumber: IdNumber;
    genes: string;
    birthday?: Time;
}): Promise<{
    sex: string;
    weight: [] | [bigint];
    name: string;
    picture: [] | [_ExternalBlob];
    idNumber: _IdNumber;
    genes: string;
    birthday: [] | [_Time];
}> {
    return {
        sex: value.sex,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        name: value.name,
        picture: value.picture ? candid_some(await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.picture)) : candid_none(),
        idNumber: value.idNumber,
        genes: value.genes,
        birthday: value.birthday ? candid_some(value.birthday) : candid_none()
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clutchNumber: bigint;
    outcomeNotes: string;
    numSlugs: bigint;
    dateEggsLaid: Time;
    sireId: AnimalId;
    numEggsLaid: bigint;
    damId: AnimalId;
    hatchDate?: Time;
    numHatched: bigint;
}): {
    clutchNumber: bigint;
    outcomeNotes: string;
    numSlugs: bigint;
    dateEggsLaid: _Time;
    sireId: _AnimalId;
    numEggsLaid: bigint;
    damId: _AnimalId;
    hatchDate: [] | [_Time];
    numHatched: bigint;
} {
    return {
        clutchNumber: value.clutchNumber,
        outcomeNotes: value.outcomeNotes,
        numSlugs: value.numSlugs,
        dateEggsLaid: value.dateEggsLaid,
        sireId: value.sireId,
        numEggsLaid: value.numEggsLaid,
        damId: value.damId,
        hatchDate: value.hatchDate ? candid_some(value.hatchDate) : candid_none(),
        numHatched: value.numHatched
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BulkSnakeEntry>): Promise<Array<_BulkSnakeEntry>> {
    return await Promise.all(value.map(async (x)=>await to_candid_BulkSnakeEntry_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
