/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Animal {
  'id' : AnimalId,
  'sex' : string,
  'weight' : [] | [bigint],
  'name' : string,
  'picture' : [] | [ExternalBlob],
  'idNumber' : IdNumber,
  'genes' : string,
  'birthday' : [] | [Time],
}
export type AnimalId = string;
export interface AnimalWeightUpdate { 'weight' : bigint, 'animalId' : AnimalId }
export interface AnimalWithDaysSinceLastEvents {
  'daysSinceLastPairing' : [] | [bigint],
  'animal' : Animal,
  'daysSinceLastClutch' : [] | [bigint],
  'daysSinceLastTubChange' : [] | [bigint],
  'daysSinceLastMeal' : [] | [bigint],
  'daysSinceLastShed' : [] | [bigint],
}
export interface AnimalWithDaysSinceLastMeal {
  'animal' : Animal,
  'daysSinceLastMeal' : [] | [bigint],
}
export interface AnimalWithDaysSinceLastMealAndPairing {
  'daysSinceLastPairing' : [] | [bigint],
  'animal' : Animal,
  'daysSinceLastMeal' : [] | [bigint],
}
export interface BulkSnakeEntry {
  'sex' : string,
  'weight' : [] | [bigint],
  'name' : string,
  'picture' : [] | [ExternalBlob],
  'idNumber' : IdNumber,
  'genes' : string,
  'birthday' : [] | [Time],
}
export interface ClutchEntry {
  'id' : bigint,
  'animalId' : AnimalId,
  'notes' : string,
  'timestamp' : Time,
}
export type ClutchId = bigint;
export interface ClutchInput {
  'clutchNumber' : bigint,
  'outcomeNotes' : string,
  'numSlugs' : bigint,
  'dateEggsLaid' : Time,
  'sireId' : AnimalId,
  'numEggsLaid' : bigint,
  'damId' : AnimalId,
  'hatchDate' : [] | [Time],
  'numHatched' : bigint,
}
export interface ClutchRecord {
  'id' : ClutchId,
  'clutchNumber' : bigint,
  'outcomeNotes' : string,
  'numSlugs' : bigint,
  'dateEggsLaid' : Time,
  'sireId' : AnimalId,
  'numEggsLaid' : bigint,
  'damId' : AnimalId,
  'hatchDate' : [] | [Time],
  'numHatched' : bigint,
}
export type ExternalBlob = Uint8Array;
export type IdNumber = string;
export interface Meal {
  'id' : MealId,
  'animalId' : AnimalId,
  'timestamp' : Time,
  'details' : string,
}
export type MealId = bigint;
export interface PairingEntry {
  'id' : PairingId,
  'animalId' : AnimalId,
  'notes' : string,
  'timestamp' : Time,
}
export type PairingId = bigint;
export interface ShedEntry {
  'id' : ShedId,
  'animalId' : AnimalId,
  'timestamp' : Time,
}
export type ShedId = bigint;
export type Time = bigint;
export interface TubChangeEntry {
  'id' : TubChangeId,
  'animalId' : AnimalId,
  'timestamp' : Time,
}
export type TubChangeId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry {
  'id' : WeightId,
  'weight' : bigint,
  'animalId' : AnimalId,
  'timestamp' : Time,
}
export type WeightId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAnimal' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [Time],
      [] | [bigint],
      [] | [ExternalBlob],
      IdNumber,
    ],
    AnimalId
  >,
  'addBulkMealsForSelectedAnimals' : ActorMethod<
    [Array<AnimalId>, string, Time],
    Array<MealId>
  >,
  'addBulkSnakes' : ActorMethod<[Array<BulkSnakeEntry>], Array<AnimalId>>,
  'addBulkWeightEntries' : ActorMethod<[Array<WeightEntry>], undefined>,
  'addBulkWeightsForSelectedAnimals' : ActorMethod<
    [Array<AnimalWeightUpdate>],
    undefined
  >,
  'addClutchRecord' : ActorMethod<[ClutchInput], ClutchId>,
  'addMeal' : ActorMethod<[AnimalId, string, Time], MealId>,
  'addPairingEntry' : ActorMethod<[AnimalId, Time, string], PairingId>,
  'addWeightEntry' : ActorMethod<[AnimalId, bigint, Time], WeightId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAnimal' : ActorMethod<[AnimalId], undefined>,
  'deleteClutchEntry' : ActorMethod<[bigint], undefined>,
  'deleteClutchRecord' : ActorMethod<[ClutchId], undefined>,
  'deleteMeal' : ActorMethod<[MealId], undefined>,
  'deletePairingEntry' : ActorMethod<[PairingId], undefined>,
  'deleteShedEntry' : ActorMethod<[ShedId], undefined>,
  'deleteTubChangeEntry' : ActorMethod<[TubChangeId], undefined>,
  'deleteWeightEntry' : ActorMethod<[WeightId], undefined>,
  'editAnimal' : ActorMethod<
    [
      AnimalId,
      string,
      string,
      string,
      [] | [Time],
      [] | [bigint],
      [] | [ExternalBlob],
      IdNumber,
    ],
    undefined
  >,
  'editClutchEntry' : ActorMethod<[bigint, AnimalId, Time, string], undefined>,
  'editClutchRecord' : ActorMethod<[ClutchId, ClutchInput], undefined>,
  'editMeal' : ActorMethod<[MealId, string], undefined>,
  'editPairingEntry' : ActorMethod<[PairingId, Time, string], undefined>,
  'editShedEntry' : ActorMethod<[ShedId, AnimalId, Time], undefined>,
  'editTubChangeEntry' : ActorMethod<[TubChangeId, AnimalId, Time], undefined>,
  'editWeightEntry' : ActorMethod<[WeightId, bigint, Time], undefined>,
  'getAnimalById' : ActorMethod<[AnimalId], [] | [Animal]>,
  'getAnimals' : ActorMethod<[], Array<Animal>>,
  'getAnimalsWithDaysSinceLastEvents' : ActorMethod<
    [],
    Array<AnimalWithDaysSinceLastEvents>
  >,
  'getAnimalsWithDaysSinceLastMeal' : ActorMethod<
    [],
    Array<AnimalWithDaysSinceLastMeal>
  >,
  'getAnimalsWithDaysSinceLastMealAndPairing' : ActorMethod<
    [],
    Array<AnimalWithDaysSinceLastMealAndPairing>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClutchHistoryForAnimal' : ActorMethod<[AnimalId], Array<ClutchEntry>>,
  'getClutchRecords' : ActorMethod<[], Array<ClutchRecord>>,
  'getCustomHeading' : ActorMethod<[], string>,
  'getLastWaterChange' : ActorMethod<[], [] | [Time]>,
  'getMealsForAnimal' : ActorMethod<[AnimalId], Array<Meal>>,
  'getPairingHistoryForAnimal' : ActorMethod<[AnimalId], Array<PairingEntry>>,
  'getShedHistoryForAnimal' : ActorMethod<[AnimalId], Array<ShedEntry>>,
  'getTubChangeHistoryForAnimal' : ActorMethod<
    [AnimalId],
    Array<TubChangeEntry>
  >,
  'getUserLogo' : ActorMethod<[], [] | [ExternalBlob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightHistoryForAnimal' : ActorMethod<[AnimalId], Array<WeightEntry>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logShedAndTubChange' : ActorMethod<[AnimalId], undefined>,
  'logShedOnly' : ActorMethod<[AnimalId], undefined>,
  'logTubChangeOnly' : ActorMethod<[AnimalId], undefined>,
  'recordClutch' : ActorMethod<[AnimalId, string], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomHeading' : ActorMethod<[string], undefined>,
  'updateWaterChange' : ActorMethod<[], undefined>,
  'uploadUserLogo' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];