/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const IdNumber = IDL.Text;
export const AnimalId = IDL.Text;
export const MealId = IDL.Nat;
export const BulkSnakeEntry = IDL.Record({
  'sex' : IDL.Text,
  'weight' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'picture' : IDL.Opt(ExternalBlob),
  'idNumber' : IdNumber,
  'genes' : IDL.Text,
  'birthday' : IDL.Opt(Time),
});
export const WeightId = IDL.Nat;
export const WeightEntry = IDL.Record({
  'id' : WeightId,
  'weight' : IDL.Nat,
  'animalId' : AnimalId,
  'timestamp' : Time,
});
export const AnimalWeightUpdate = IDL.Record({
  'weight' : IDL.Nat,
  'animalId' : AnimalId,
});
export const ClutchInput = IDL.Record({
  'clutchNumber' : IDL.Nat,
  'outcomeNotes' : IDL.Text,
  'numSlugs' : IDL.Nat,
  'dateEggsLaid' : Time,
  'sireId' : AnimalId,
  'numEggsLaid' : IDL.Nat,
  'damId' : AnimalId,
  'hatchDate' : IDL.Opt(Time),
  'numHatched' : IDL.Nat,
});
export const ClutchId = IDL.Nat;
export const PairingId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShedId = IDL.Nat;
export const TubChangeId = IDL.Nat;
export const Animal = IDL.Record({
  'id' : AnimalId,
  'sex' : IDL.Text,
  'weight' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'picture' : IDL.Opt(ExternalBlob),
  'idNumber' : IdNumber,
  'genes' : IDL.Text,
  'birthday' : IDL.Opt(Time),
});
export const AnimalWithDaysSinceLastEvents = IDL.Record({
  'daysSinceLastPairing' : IDL.Opt(IDL.Int),
  'animal' : Animal,
  'daysSinceLastClutch' : IDL.Opt(IDL.Int),
  'daysSinceLastTubChange' : IDL.Opt(IDL.Int),
  'daysSinceLastMeal' : IDL.Opt(IDL.Int),
  'daysSinceLastShed' : IDL.Opt(IDL.Int),
});
export const AnimalWithDaysSinceLastMeal = IDL.Record({
  'animal' : Animal,
  'daysSinceLastMeal' : IDL.Opt(IDL.Int),
});
export const AnimalWithDaysSinceLastMealAndPairing = IDL.Record({
  'daysSinceLastPairing' : IDL.Opt(IDL.Int),
  'animal' : Animal,
  'daysSinceLastMeal' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ClutchEntry = IDL.Record({
  'id' : IDL.Nat,
  'animalId' : AnimalId,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const ClutchRecord = IDL.Record({
  'id' : ClutchId,
  'clutchNumber' : IDL.Nat,
  'outcomeNotes' : IDL.Text,
  'numSlugs' : IDL.Nat,
  'dateEggsLaid' : Time,
  'sireId' : AnimalId,
  'numEggsLaid' : IDL.Nat,
  'damId' : AnimalId,
  'hatchDate' : IDL.Opt(Time),
  'numHatched' : IDL.Nat,
});
export const Meal = IDL.Record({
  'id' : MealId,
  'animalId' : AnimalId,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const PairingEntry = IDL.Record({
  'id' : PairingId,
  'animalId' : AnimalId,
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const ShedEntry = IDL.Record({
  'id' : ShedId,
  'animalId' : AnimalId,
  'timestamp' : Time,
});
export const TubChangeEntry = IDL.Record({
  'id' : TubChangeId,
  'animalId' : AnimalId,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAnimal' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(Time),
        IDL.Opt(IDL.Nat),
        IDL.Opt(ExternalBlob),
        IdNumber,
      ],
      [AnimalId],
      [],
    ),
  'addBulkMealsForSelectedAnimals' : IDL.Func(
      [IDL.Vec(AnimalId), IDL.Text, Time],
      [IDL.Vec(MealId)],
      [],
    ),
  'addBulkSnakes' : IDL.Func(
      [IDL.Vec(BulkSnakeEntry)],
      [IDL.Vec(AnimalId)],
      [],
    ),
  'addBulkWeightEntries' : IDL.Func([IDL.Vec(WeightEntry)], [], []),
  'addBulkWeightsForSelectedAnimals' : IDL.Func(
      [IDL.Vec(AnimalWeightUpdate)],
      [],
      [],
    ),
  'addClutchRecord' : IDL.Func([ClutchInput], [ClutchId], []),
  'addMeal' : IDL.Func([AnimalId, IDL.Text, Time], [MealId], []),
  'addPairingEntry' : IDL.Func([AnimalId, Time, IDL.Text], [PairingId], []),
  'addWeightEntry' : IDL.Func([AnimalId, IDL.Nat, Time], [WeightId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAnimal' : IDL.Func([AnimalId], [], []),
  'deleteClutchEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteClutchRecord' : IDL.Func([ClutchId], [], []),
  'deleteMeal' : IDL.Func([MealId], [], []),
  'deletePairingEntry' : IDL.Func([PairingId], [], []),
  'deleteShedEntry' : IDL.Func([ShedId], [], []),
  'deleteTubChangeEntry' : IDL.Func([TubChangeId], [], []),
  'deleteWeightEntry' : IDL.Func([WeightId], [], []),
  'editAnimal' : IDL.Func(
      [
        AnimalId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(Time),
        IDL.Opt(IDL.Nat),
        IDL.Opt(ExternalBlob),
        IdNumber,
      ],
      [],
      [],
    ),
  'editClutchEntry' : IDL.Func([IDL.Nat, AnimalId, Time, IDL.Text], [], []),
  'editClutchRecord' : IDL.Func([ClutchId, ClutchInput], [], []),
  'editMeal' : IDL.Func([MealId, IDL.Text], [], []),
  'editPairingEntry' : IDL.Func([PairingId, Time, IDL.Text], [], []),
  'editShedEntry' : IDL.Func([ShedId, AnimalId, Time], [], []),
  'editTubChangeEntry' : IDL.Func([TubChangeId, AnimalId, Time], [], []),
  'editWeightEntry' : IDL.Func([WeightId, IDL.Nat, Time], [], []),
  'getAnimalById' : IDL.Func([AnimalId], [IDL.Opt(Animal)], ['query']),
  'getAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
  'getAnimalsWithDaysSinceLastEvents' : IDL.Func(
      [],
      [IDL.Vec(AnimalWithDaysSinceLastEvents)],
      ['query'],
    ),
  'getAnimalsWithDaysSinceLastMeal' : IDL.Func(
      [],
      [IDL.Vec(AnimalWithDaysSinceLastMeal)],
      ['query'],
    ),
  'getAnimalsWithDaysSinceLastMealAndPairing' : IDL.Func(
      [],
      [IDL.Vec(AnimalWithDaysSinceLastMealAndPairing)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClutchHistoryForAnimal' : IDL.Func(
      [AnimalId],
      [IDL.Vec(ClutchEntry)],
      ['query'],
    ),
  'getClutchRecords' : IDL.Func([], [IDL.Vec(ClutchRecord)], ['query']),
  'getCustomHeading' : IDL.Func([], [IDL.Text], ['query']),
  'getLastWaterChange' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getMealsForAnimal' : IDL.Func([AnimalId], [IDL.Vec(Meal)], ['query']),
  'getPairingHistoryForAnimal' : IDL.Func(
      [AnimalId],
      [IDL.Vec(PairingEntry)],
      ['query'],
    ),
  'getShedHistoryForAnimal' : IDL.Func(
      [AnimalId],
      [IDL.Vec(ShedEntry)],
      ['query'],
    ),
  'getTubChangeHistoryForAnimal' : IDL.Func(
      [AnimalId],
      [IDL.Vec(TubChangeEntry)],
      ['query'],
    ),
  'getUserLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightHistoryForAnimal' : IDL.Func(
      [AnimalId],
      [IDL.Vec(WeightEntry)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logShedAndTubChange' : IDL.Func([AnimalId], [], []),
  'logShedOnly' : IDL.Func([AnimalId], [], []),
  'logTubChangeOnly' : IDL.Func([AnimalId], [], []),
  'recordClutch' : IDL.Func([AnimalId, IDL.Text], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomHeading' : IDL.Func([IDL.Text], [], []),
  'updateWaterChange' : IDL.Func([], [], []),
  'uploadUserLogo' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const IdNumber = IDL.Text;
  const AnimalId = IDL.Text;
  const MealId = IDL.Nat;
  const BulkSnakeEntry = IDL.Record({
    'sex' : IDL.Text,
    'weight' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'picture' : IDL.Opt(ExternalBlob),
    'idNumber' : IdNumber,
    'genes' : IDL.Text,
    'birthday' : IDL.Opt(Time),
  });
  const WeightId = IDL.Nat;
  const WeightEntry = IDL.Record({
    'id' : WeightId,
    'weight' : IDL.Nat,
    'animalId' : AnimalId,
    'timestamp' : Time,
  });
  const AnimalWeightUpdate = IDL.Record({
    'weight' : IDL.Nat,
    'animalId' : AnimalId,
  });
  const ClutchInput = IDL.Record({
    'clutchNumber' : IDL.Nat,
    'outcomeNotes' : IDL.Text,
    'numSlugs' : IDL.Nat,
    'dateEggsLaid' : Time,
    'sireId' : AnimalId,
    'numEggsLaid' : IDL.Nat,
    'damId' : AnimalId,
    'hatchDate' : IDL.Opt(Time),
    'numHatched' : IDL.Nat,
  });
  const ClutchId = IDL.Nat;
  const PairingId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShedId = IDL.Nat;
  const TubChangeId = IDL.Nat;
  const Animal = IDL.Record({
    'id' : AnimalId,
    'sex' : IDL.Text,
    'weight' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'picture' : IDL.Opt(ExternalBlob),
    'idNumber' : IdNumber,
    'genes' : IDL.Text,
    'birthday' : IDL.Opt(Time),
  });
  const AnimalWithDaysSinceLastEvents = IDL.Record({
    'daysSinceLastPairing' : IDL.Opt(IDL.Int),
    'animal' : Animal,
    'daysSinceLastClutch' : IDL.Opt(IDL.Int),
    'daysSinceLastTubChange' : IDL.Opt(IDL.Int),
    'daysSinceLastMeal' : IDL.Opt(IDL.Int),
    'daysSinceLastShed' : IDL.Opt(IDL.Int),
  });
  const AnimalWithDaysSinceLastMeal = IDL.Record({
    'animal' : Animal,
    'daysSinceLastMeal' : IDL.Opt(IDL.Int),
  });
  const AnimalWithDaysSinceLastMealAndPairing = IDL.Record({
    'daysSinceLastPairing' : IDL.Opt(IDL.Int),
    'animal' : Animal,
    'daysSinceLastMeal' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ClutchEntry = IDL.Record({
    'id' : IDL.Nat,
    'animalId' : AnimalId,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const ClutchRecord = IDL.Record({
    'id' : ClutchId,
    'clutchNumber' : IDL.Nat,
    'outcomeNotes' : IDL.Text,
    'numSlugs' : IDL.Nat,
    'dateEggsLaid' : Time,
    'sireId' : AnimalId,
    'numEggsLaid' : IDL.Nat,
    'damId' : AnimalId,
    'hatchDate' : IDL.Opt(Time),
    'numHatched' : IDL.Nat,
  });
  const Meal = IDL.Record({
    'id' : MealId,
    'animalId' : AnimalId,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const PairingEntry = IDL.Record({
    'id' : PairingId,
    'animalId' : AnimalId,
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const ShedEntry = IDL.Record({
    'id' : ShedId,
    'animalId' : AnimalId,
    'timestamp' : Time,
  });
  const TubChangeEntry = IDL.Record({
    'id' : TubChangeId,
    'animalId' : AnimalId,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAnimal' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Time),
          IDL.Opt(IDL.Nat),
          IDL.Opt(ExternalBlob),
          IdNumber,
        ],
        [AnimalId],
        [],
      ),
    'addBulkMealsForSelectedAnimals' : IDL.Func(
        [IDL.Vec(AnimalId), IDL.Text, Time],
        [IDL.Vec(MealId)],
        [],
      ),
    'addBulkSnakes' : IDL.Func(
        [IDL.Vec(BulkSnakeEntry)],
        [IDL.Vec(AnimalId)],
        [],
      ),
    'addBulkWeightEntries' : IDL.Func([IDL.Vec(WeightEntry)], [], []),
    'addBulkWeightsForSelectedAnimals' : IDL.Func(
        [IDL.Vec(AnimalWeightUpdate)],
        [],
        [],
      ),
    'addClutchRecord' : IDL.Func([ClutchInput], [ClutchId], []),
    'addMeal' : IDL.Func([AnimalId, IDL.Text, Time], [MealId], []),
    'addPairingEntry' : IDL.Func([AnimalId, Time, IDL.Text], [PairingId], []),
    'addWeightEntry' : IDL.Func([AnimalId, IDL.Nat, Time], [WeightId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAnimal' : IDL.Func([AnimalId], [], []),
    'deleteClutchEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteClutchRecord' : IDL.Func([ClutchId], [], []),
    'deleteMeal' : IDL.Func([MealId], [], []),
    'deletePairingEntry' : IDL.Func([PairingId], [], []),
    'deleteShedEntry' : IDL.Func([ShedId], [], []),
    'deleteTubChangeEntry' : IDL.Func([TubChangeId], [], []),
    'deleteWeightEntry' : IDL.Func([WeightId], [], []),
    'editAnimal' : IDL.Func(
        [
          AnimalId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(Time),
          IDL.Opt(IDL.Nat),
          IDL.Opt(ExternalBlob),
          IdNumber,
        ],
        [],
        [],
      ),
    'editClutchEntry' : IDL.Func([IDL.Nat, AnimalId, Time, IDL.Text], [], []),
    'editClutchRecord' : IDL.Func([ClutchId, ClutchInput], [], []),
    'editMeal' : IDL.Func([MealId, IDL.Text], [], []),
    'editPairingEntry' : IDL.Func([PairingId, Time, IDL.Text], [], []),
    'editShedEntry' : IDL.Func([ShedId, AnimalId, Time], [], []),
    'editTubChangeEntry' : IDL.Func([TubChangeId, AnimalId, Time], [], []),
    'editWeightEntry' : IDL.Func([WeightId, IDL.Nat, Time], [], []),
    'getAnimalById' : IDL.Func([AnimalId], [IDL.Opt(Animal)], ['query']),
    'getAnimals' : IDL.Func([], [IDL.Vec(Animal)], ['query']),
    'getAnimalsWithDaysSinceLastEvents' : IDL.Func(
        [],
        [IDL.Vec(AnimalWithDaysSinceLastEvents)],
        ['query'],
      ),
    'getAnimalsWithDaysSinceLastMeal' : IDL.Func(
        [],
        [IDL.Vec(AnimalWithDaysSinceLastMeal)],
        ['query'],
      ),
    'getAnimalsWithDaysSinceLastMealAndPairing' : IDL.Func(
        [],
        [IDL.Vec(AnimalWithDaysSinceLastMealAndPairing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClutchHistoryForAnimal' : IDL.Func(
        [AnimalId],
        [IDL.Vec(ClutchEntry)],
        ['query'],
      ),
    'getClutchRecords' : IDL.Func([], [IDL.Vec(ClutchRecord)], ['query']),
    'getCustomHeading' : IDL.Func([], [IDL.Text], ['query']),
    'getLastWaterChange' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getMealsForAnimal' : IDL.Func([AnimalId], [IDL.Vec(Meal)], ['query']),
    'getPairingHistoryForAnimal' : IDL.Func(
        [AnimalId],
        [IDL.Vec(PairingEntry)],
        ['query'],
      ),
    'getShedHistoryForAnimal' : IDL.Func(
        [AnimalId],
        [IDL.Vec(ShedEntry)],
        ['query'],
      ),
    'getTubChangeHistoryForAnimal' : IDL.Func(
        [AnimalId],
        [IDL.Vec(TubChangeEntry)],
        ['query'],
      ),
    'getUserLogo' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightHistoryForAnimal' : IDL.Func(
        [AnimalId],
        [IDL.Vec(WeightEntry)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logShedAndTubChange' : IDL.Func([AnimalId], [], []),
    'logShedOnly' : IDL.Func([AnimalId], [], []),
    'logTubChangeOnly' : IDL.Func([AnimalId], [], []),
    'recordClutch' : IDL.Func([AnimalId, IDL.Text], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomHeading' : IDL.Func([IDL.Text], [], []),
    'updateWaterChange' : IDL.Func([], [], []),
    'uploadUserLogo' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };